// Code generated by juaz. DO NOT EDIT.
// versions: v1.0.0
// source: user.juaz

package main

// User data model for the user structure
type User struct {
	UserId *int64  `json:"user_id,omitempty"`
	Name   *string `json:"name,omitempty"`
}
